# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iVdYjRTLcQh5utUfqnjlCPovFcFiij4c
"""

from flask import Flask, render_template, request, redirect, url_for
from tensorflow.keras.models import load_model
from tensorflow.keras.preprocessing import image
import numpy as np
import os

app = Flask(__name__)
app.config['UPLOAD_FOLDER'] = 'uploads'

# Load the trained model
model = load_model('rice.h5')

# Class labels (update if different)
class_names = [ 'Arborio', 'Basmati','Ipsala' ,'Jasmine','karacadag']

# Home route
@app.route('/')
def home():
    return render_template('index.html')

# Details page
@app.route('/details')
def details():
    return render_template('details.html')

# Contact page
@app.route('/contact')
def contact():
    return render_template('contact.html')

# Predict page
@app.route('/predict', methods=['GET', 'POST'])
def predict():
    prediction = None
    if request.method == 'POST':
        file = request.files['file']
        if file:
            filepath = os.path.join(app.config['UPLOAD_FOLDER'], file.filename)
            file.save(filepath)

            # Preprocess image
            img = image.load_img(filepath, target_size=(250, 250))
            img_array = image.img_to_array(img) / 255.0
            img_array = np.expand_dims(img_array, axis=0)

            pred = model.predict(img_array)
            predicted_class = class_names[np.argmax(pred)]
            prediction = f"{predicted_class}"

    return render_template('predict.html', prediction=prediction)

if __name__ == '__main__':
    app.run(debug=True, use_reloader=False)